### ISSUE TITLE
Why does this library prohibit using System.Text.Json 9.0?

### ISSUE THREAD

**Issue by stephentoub** [microsoft/OpenApi.ApiManifest#116]
https://github.com/microsoft/OpenApi.ApiManifest/blob/0c2ad4c4796b734e653787702b299be480b37880/src/lib/apimanifest.csproj#L38

**Comment by martincostello** [comment]
Just found this via a report to Swashbuckle.AspNetCore core claiming it didn't support .NET 9: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/3145

**Comment by raffaeler** [comment]
Any forecast for the updated Nuget package?
I currently only see the  0.5.4-preview on Nuget.
Thanks!

**Comment by baywet** [comment]
0.5.6 has [been made available](https://www.nuget.org/packages/Microsoft.OpenApi.ApiManifest/0.5.6-preview) on nuget about 3 days ago.
Let us know if you have any additional comments or questions.

**Comment by stephentoub** [comment]
> 0.5.6 has [been made available](https://www.nuget.org/packages/Microsoft.OpenApi.ApiManifest/0.5.6-preview) on nuget about 3 days ago. Let us know if you have any additional comments or questions.

Do you own Microsoft.Plugins.Manifest as well? If yes, can you push a new version of that? It also has the < 9.0 limitation, and is also preventing folks from upgrading.

**Comment by baywet** [comment]
yes we do, for some reason the repo is still private...
The fix already has been implemented, all that's left is to release a new version.
https://github.com/microsoft/Microsoft.Plugins.Manifest/pull/385

Can you please reach out to @petrhollayms internally to coordinate the release please? CC @SilasKenneth

**Comment by raffaeler** [comment]
I directly referenced the latest preview of `OpenApi.ApiManifest` in order to get rid of the warning.
It's quite a dirty workaround, but at least I could finalize the update to .NET 9 libraries.

**Comment by baywet** [comment]
For others reading, we released the other library.

**Comment by raffaeler** [comment]
> For others reading, we released the other library.

@baywet 
I guess I will have to wait for the ASP.NET team to repackage their dependencies with this one, before I can get this fix, right?

**Comment by baywet** [comment]
I wasn't aware that this repository and the other one were pulled by the aspnet core dependencies. 
Can you run dotnet nuget why on your project for both dependencies and share the results here please?
