### ISSUE TITLE
Move code to generate AIPluginManifest from hidi to this library

### ISSUE THREAD

**Issue by darrelmiller** [microsoft/OpenApi.ApiManifest#4]
https://github.com/microsoft/OpenAPI.NET/blob/d9e7a9ee18f823caeed006178b67db1874800f2d/src/Microsoft.OpenApi.Hidi/OpenApiService.cs#L701

**Comment by peombwa** [comment]
Constraints:
- API manifest is a class library. We shouldn't write to the file system. Hidi will call the conversion method to write the OpenAI manifest to the file system.
- The method should be called from a valid instance of an ApiManifest.
